server:
  port: 8083

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    # Defaults to localhost if run outside Docker, but overrides dynamically
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:3307}/${SPRING_DATASOURCE_DB:hotel_db}?createDatabaseIfNotExist=true&seSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:

      pool-name: orderServiceHikariPool
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000

      auto-commit: false

      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true     # Allows displaying keys prefixed with "info.*"
    java:
      enabled: true     # Shows the container's Java version (Java 21)
    os:
      enabled: true     # Shows the container's operating system info (Alpine Linux)

# Optional: Add custom key-value pairs that you want displayed when hitting the endpoint
info:
  app:
    name: Hotel Management Microservice
    description: Dynamic hotel search backend tracking lodging inventories.
    version: 1.0.0

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
